
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktrbaiijlhssaxpxpzhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cmJhaWlqbGhzc2F4cHhwemhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NjE2MDksImV4cCI6MjA1NjIzNzYwOX0.k2MVB81LUxuAc2PMJOgO8U4yk_lLbNzTkCbqErd0nqE";

// Debugging the client creation
console.log("Creating Supabase client with URL:", SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Make a simple call to verify the client is working
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    console.error("Error initializing Supabase client:", error);
  } else {
    console.log("Supabase client initialized successfully", data.session ? "User is logged in" : "No active session");
  }
});
